"use client";

import { useState } from "react";
import UploadBox from "@/components/UploadBox";
import ResultBox from "@/components/ResultBox";

interface DetectionResult {
  success: boolean;
  ai_generated?: boolean;
  confidence?: number;
  artificial_score?: number;
  human_score?: number;
  detected_model?: string | null;
  message?: string;
}

export default function Home() {
  const [file, setFile] = useState<File | null>(null);
  const [result, setResult] = useState<DetectionResult | null>(null);
  const [isLoading, setIsLoading] = useState(false);

  const handleFileSelect = (selectedFile: File) => {
    setFile(selectedFile);
    setResult(null);
  };

  const handleDetect = async () => {
    if (!file) return;

    setIsLoading(true);
    setResult(null);

    try {
      const formData = new FormData();
      formData.append("file", file);

      const response = await fetch("/api/detect", {
        method: "POST",
        body: formData,
      });

      const data = await response.json();
      setResult(data);
    } catch {
      setResult({ success: false, message: "Failed to connect to server" });
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-[var(--color-dark-bg)] relative overflow-hidden">
      {/* Background glow effects */}
      <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[600px] h-[400px] bg-purple-600/10 rounded-full blur-[120px] pointer-events-none" />
      <div className="absolute bottom-0 right-0 w-[400px] h-[300px] bg-violet-600/5 rounded-full blur-[100px] pointer-events-none" />

      <main className="relative z-10 max-w-xl mx-auto px-4 py-20">
        {/* Header */}
        <div className="text-center mb-12">
          <div className="inline-flex items-center gap-2 border border-purple-500/30 bg-purple-500/10 text-purple-400 text-xs font-semibold px-4 py-1.5 rounded-full mb-5 backdrop-blur-sm">
            <span className="w-1.5 h-1.5 bg-green-400 rounded-full animate-pulse" />
            FutureStore AI Tool
          </div>
          <h1 className="text-4xl font-extrabold text-white tracking-tight">
            AI Content Detector
          </h1>
          <p className="text-slate-400 mt-3 text-sm leading-relaxed max-w-md mx-auto">
            Upload an image to verify if it was generated by AI.
            <br />
            Powered by advanced detection models.
          </p>
        </div>

        {/* Upload */}
        <div className="space-y-4">
          <UploadBox onFileSelect={handleFileSelect} isLoading={isLoading} />

          {file && (
            <button
              onClick={handleDetect}
              disabled={isLoading}
              className="w-full py-3.5 bg-purple-600 hover:bg-purple-700 text-white font-semibold rounded-xl transition-all duration-200 disabled:opacity-50 disabled:cursor-not-allowed cursor-pointer active:scale-[0.98] shadow-lg shadow-purple-600/25"
            >
              {isLoading ? "Analyzing..." : "Detect Content"}
            </button>
          )}
        </div>

        {/* Result */}
        <div className="mt-6">
          <ResultBox result={result} isLoading={isLoading} />
        </div>

        {/* Footer */}
        <div className="mt-16 text-center">
          <p className="text-slate-600 text-xs">
            Part of the{" "}
            <a className="text-purple-400 font-medium" target="_blank" href="https://futurestoreai.com">futurestoreai.com</a>{" "}
            ecosystem
          </p>
        </div>
      </main>
    </div>
  );
}
