"use client";

import { useState } from "react";
import UploadBox from "@/components/UploadBox";
import ResultBox from "@/components/ResultBox";

interface DetectionResult {
  success: boolean;
  ai_generated?: boolean;
  confidence?: number;
  detected_model?: string | null;
  message?: string;
}

export default function Home() {
  const [file, setFile] = useState<File | null>(null);
  const [result, setResult] = useState<DetectionResult | null>(null);
  const [isLoading, setIsLoading] = useState(false);

  const handleFileSelect = (selectedFile: File) => {
    setFile(selectedFile);
    setResult(null);
  };

  const handleDetect = async () => {
    if (!file) return;

    setIsLoading(true);
    setResult(null);

    try {
      const formData = new FormData();
      formData.append("file", file);

      const response = await fetch("/api/detect", {
        method: "POST",
        body: formData,
      });

      const data = await response.json();
      setResult(data);
    } catch {
      setResult({ success: false, message: "Failed to connect to server" });
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-zinc-50 via-white to-indigo-50">
      <main className="max-w-xl mx-auto px-4 py-16">
        {/* Header */}
        <div className="text-center mb-10">
          <div className="inline-flex items-center gap-2 bg-indigo-100 text-indigo-700 text-xs font-semibold px-3 py-1 rounded-full mb-4">
            <span className="w-1.5 h-1.5 bg-indigo-500 rounded-full animate-pulse" />
            AI Detection
          </div>
          <h1 className="text-3xl font-bold text-zinc-900 tracking-tight">
            AI Content Detector
          </h1>
          <p className="text-zinc-500 mt-2 text-sm">
            Upload an image to check if it was generated by AI
          </p>
        </div>

        {/* Upload */}
        <div className="space-y-4">
          <UploadBox onFileSelect={handleFileSelect} isLoading={isLoading} />

          {/* Detect button */}
          {file && (
            <button
              onClick={handleDetect}
              disabled={isLoading}
              className="w-full py-3.5 bg-indigo-600 hover:bg-indigo-700 text-white font-semibold rounded-xl transition-all duration-200 disabled:opacity-50 disabled:cursor-not-allowed cursor-pointer active:scale-[0.98]"
            >
              {isLoading ? "Analyzing..." : "Detect Content"}
            </button>
          )}
        </div>

        {/* Result */}
        <div className="mt-6">
          <ResultBox result={result} isLoading={isLoading} />
        </div>
      </main>
    </div>
  );
}
