"use client";

import { useState } from "react";
import UploadBox from "@/components/UploadBox";
import ResultBox from "@/components/ResultBox";
import Link from "next/link";

import { DetectionResponse } from "@/components/ResultBox";

export default function Home() {
  const [activeTab, setActiveTab] = useState<"file" | "text">("file");
  const [file, setFile] = useState<File | null>(null);
  const [text, setText] = useState("");
  const [result, setResult] = useState<DetectionResponse | null>(null);
  const [isLoading, setIsLoading] = useState(false);

  const handleTabChange = (tab: "file" | "text") => {
    setActiveTab(tab);
    setResult(null);
  };

  const handleFileSelect = (selectedFile: File) => {
    setFile(selectedFile);
    setResult(null);
  };

  const handleDetect = async () => {
    if (activeTab === "file" && !file) return;
    if (activeTab === "text" && !text.trim()) return;

    setIsLoading(true);
    setResult(null);

    try {
      let response;

      if (activeTab === "file") {
        const formData = new FormData();
        formData.append("file", file!);
        // Forward to Next.js API route that proxies to Python backend
        response = await fetch("/api/proxy/image/detect", {
          method: "POST",
          body: formData,
        });
      } else {
        response = await fetch("/api/detect/text", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ text: text.trim() }),
        });
      }
      
      if (!response.ok) {
        throw new Error(`Failed to fetch: ${response.status}`);
      }

      const data = await response.json();
      
      // Since /api/detect/text might still return the old `DetectionResult` format,
      // we need to gracefully handle mapping it to the new `DetectionResponse` format
      // if it hasn't been updated yet.
      if (activeTab === "text" && data.success && data.detectors) {
          setResult({
              success: true,
              data: {
                  success: true,
                  filename: "Text Input",
                  is_ai_generated: data.ai_generated,
                  confidence: data.confidence,
                  average_ai_probability: data.detectors.roberta,
                  average_real_probability: data.detectors.roberta ? 1 - data.detectors.roberta : undefined,
                  per_model: [{
                      success: true,
                      model_used: "roberta",
                      ai_probability: data.detectors.roberta
                  }]
              }
          });
      } else {
          setResult(data);
      }
      
    } catch (e: any) {
      setResult({ success: false, message: e.message || "Failed to connect to server", error: e.message });
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-[var(--color-dark-bg)] relative overflow-hidden">
      {/* Background glow effects */}
      <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[600px] h-[400px] bg-purple-600/10 rounded-full blur-[120px] pointer-events-none" />
      <div className="absolute bottom-0 right-0 w-[400px] h-[300px] bg-violet-600/5 rounded-full blur-[100px] pointer-events-none" />

      <main className="relative z-10 max-w-xl mx-auto px-4 py-20">
        {/* Header */}
        <div className="text-center mb-12">
          <Link href={"https://www.futurestoreai.com/"}>
            <img
              src="/logo.png"
              alt="FutureStore AI"
              className="h-10 mx-auto mb-6"
            />
          </Link>
          <h1 className="text-4xl font-extrabold text-white tracking-tight">
            AI Content Detector
          </h1>
          <p className="text-slate-400 mt-3 text-sm leading-relaxed max-w-md mx-auto">
            Upload a file to check if it was generated by AI.
            <br />
            Supports images, videos, and audio.
          </p>
        </div>

        {/* Tabs */}
        <div className="flex bg-[var(--color-dark-card)] p-1 rounded-xl mb-6 border border-[var(--color-dark-border)]">
          <button
            onClick={() => handleTabChange("file")}
            className={`flex-1 py-2.5 text-sm font-semibold rounded-lg transition-all duration-200 cursor-pointer ${activeTab === "file"
              ? "bg-purple-600 text-white shadow-lg shadow-purple-600/25"
              : "text-slate-400 hover:text-white hover:bg-white/5"
              }`}
          >
            Media File
          </button>
          <button
            onClick={() => handleTabChange("text")}
            className={`flex-1 py-2.5 text-sm font-semibold rounded-lg transition-all duration-200 cursor-pointer ${activeTab === "text"
              ? "bg-purple-600 text-white shadow-lg shadow-purple-600/25"
              : "text-slate-400 hover:text-white hover:bg-white/5"
              }`}
          >
            Text Content
          </button>
        </div>

        {/* Input Area */}
        <div className="space-y-4">
          {activeTab === "file" ? (
            <UploadBox onFileSelect={handleFileSelect} isLoading={isLoading} />
          ) : (
            <div className="w-full">
              <textarea
                value={text}
                onChange={(e) => {
                  setText(e.target.value);
                  setResult(null);
                }}
                disabled={isLoading}
                placeholder="Paste or type text to check if it was generated by AI..."
                className="w-full h-64 p-5 rounded-2xl bg-[var(--color-dark-card)] border border-[var(--color-dark-border)] text-slate-200 placeholder:text-slate-500 focus:outline-none focus:border-purple-500/50 focus:ring-1 focus:ring-purple-500/50 resize-none transition-all duration-200"
                maxLength={5000}
              />
              <div className="flex justify-end mt-2">
                <span className={`text-xs ${text.length >= 5000 ? "text-red-400" : "text-slate-500"}`}>
                  {text.length}/5000
                </span>
              </div>
            </div>
          )}

          {((activeTab === "file" && file) || (activeTab === "text" && text.trim().length > 0)) && (
            <button
              onClick={handleDetect}
              disabled={isLoading}
              className="w-full py-3.5 bg-purple-600 hover:bg-purple-700 text-white font-semibold rounded-xl transition-all duration-200 disabled:opacity-50 disabled:cursor-not-allowed cursor-pointer active:scale-[0.98] shadow-lg shadow-purple-600/25"
            >
              {isLoading ? "Analyzing..." : "Detect Content"}
            </button>
          )}
        </div>

        {/* Result */}
        <div className="mt-6">
          <ResultBox result={result} isLoading={isLoading} />
        </div>

        {/* Footer */}
        <div className="mt-16 text-center">
          <p className="text-slate-600 text-xs">
            Part of the{" "}
            <a className="text-purple-400 font-medium" target="_blank" href="https://futurestoreai.com">futurestoreai.com</a>{" "}
            ecosystem
          </p>
        </div>
      </main>
    </div>
  );
}
