import { InferenceClient } from "@huggingface/inference";

const hf = new InferenceClient(process.env.HUGGINGFACE_API_KEY);

const HIVE_API_KEY = process.env.HIVE_API_KEY || "";
const SDXL_MODEL = "Organika/sdxl-detector";

export interface DetectionResult {
    success: boolean;
    ai_generated: boolean;
    confidence: number;
    detectors: {
        hive: number;
        sdxl?: number;
    };
}

export async function detectWithHive(buffer: Buffer, mimeType: string): Promise<number> {
    const base64Data = buffer.toString("base64");

    const response = await fetch("https://api.thehive.ai/api/v3/hive/ai-generated-and-deepfake-content-detection", {
        method: "POST",
        headers: {
            "Authorization": `Bearer ${HIVE_API_KEY}`,
            "Content-Type": "application/json",
            "accept": "application/json"
        },
        body: JSON.stringify({
            media_metadata: true,
            input: [
                {
                    media_base64: `data:${mimeType};base64,${base64Data}`
                }
            ]
        })
    });

    if (!response.ok) {
        throw new Error(`Hive API error: ${response.status} ${response.statusText}`);
    }

    const data = await response.json();

    // Parse response
    const classes = data?.output?.[0]?.classes || [];

    const aiGeneratedScore = classes.find((c: any) => c.class === "ai_generated")?.value ?? 0;
    const deepfakeScore = classes.find((c: any) => c.class === "deepfake")?.value ?? 0;

    return Math.max(aiGeneratedScore, deepfakeScore);
}

export async function detectWithSDXL(buffer: Buffer, mimeType: string): Promise<number> {
    const uint8 = new Uint8Array(buffer);
    const blob = new Blob([uint8], { type: mimeType });

    const result = await hf.imageClassification({
        model: SDXL_MODEL,
        data: blob,
        provider: "hf-inference" // Replaced standalone constant as it's cleaner inline here
    });

    // Extract probability that the image was generated by Stable Diffusion XL.
    // Assuming the class label indicating AI is "artificial" based on typical models
    const artificialScore = result.find(
        (r) => r.label.toLowerCase() === "artificial" || r.label.toLowerCase() === "fake" || r.label.toLowerCase() === "ai-generated"
    )?.score ?? 0;

    return artificialScore;
}

export function combineScores(hiveScore: number, sdxlScore?: number): DetectionResult {
    let finalScore = hiveScore;

    const detectors: { hive: number, sdxl?: number } = {
        hive: Math.round(hiveScore * 100) / 100
    };

    if (sdxlScore !== undefined) {
        finalScore = (0.7 * hiveScore) + (0.3 * sdxlScore);
        detectors.sdxl = Math.round(sdxlScore * 100) / 100;
    }

    return {
        success: true,
        ai_generated: finalScore > 0.7,
        confidence: Math.round(finalScore * 100) / 100,
        detectors
    };
}
